### ISSUE TITLE
Multiple issues found

### ISSUE THREAD

**Issue by benooli** [Suncatcher/aws_sg_migrate#1]
Hello,

I tried your script to copy my Security Groups and ran into many many many problems.
Spent a few hours and now it's working better. I'm surprised you were able to use it- at all.

I made some changes to your script - they are not usable as-is but this is a work in progress (to get what I wanted).

here's a list of bugs I found
* using option --dest would yield a systematic error. you were not initializing the list variable correctly.
* regions global array is hard-coded. removed. your VPC ID's should not be in a public script.
* AWS added attributes like "Description", so your script would now fail. I've removed the checks that stops when they "don't know how to handle..."
*  Adding a new wait feature. When adding a security group, you cannot run the 'add ingress/egress' immediately. Need to wait for AWS to create that SG.
* Some ingress/egress are not copied. your conditions here are not helping: #if 'FromPort' not in ipp:   continue. Instead I changed the conditions below to ignore missing parameters: if 'ToPort' in ipp and ipp['ToPort'] < 0:
* You don't copy ipv6 rules. Altough I did not add this as the syntax is completely different. it'll require large rework on your script.

New Feature:
I've added a feature that allows you to copy ALL the SG's of a VPC. This is my preferred method. I did not add any parameters to your script though as I'm hardcoding it for now.

Note:
I'm also ONLY using the script with --shell. Did not see any reasons not to use this. the output is not very useful if you don't use --shell. for instance it refers to $SGID but never declares it if you don't use --shell.. which is strange.

[aws_sg_migrate.zip](https://github.com/Suncatcher/aws_sg_migrate/files/2144695/aws_sg_migrate.zip)

**Comment by Suncatcher** [comment]
Thanks for your valuable comment, I will review and will report soon.

**Comment by Suncatcher** [comment]
Hi, benooli,
I made [a new version of the script](https://github.com/Suncatcher/aws_sg_migrate/releases/tag/v.0.2), try it please. Some of the issues you described are already fixed in it.
The work is still ongoing.

**Comment by Suncatcher** [comment]
closed as no response was given
