### ISSUE TITLE
Issues with Descriptions in IpRanges

### ISSUE THREAD

**Issue by warriorsoul15** [Suncatcher/aws_sg_migrate#2]
When I execute the script to copy a given SG it fails on:

Error: Don't know how to handlekey Description in IpRanges

It doesnt appear to handle descriptions on individual SG rules?

**Comment by warriorsoul15** [comment]
On a related note when i try the script against an SG without any rule descriptions it still dies on null list entries.

Traceback (most recent call last):
  File "aws_sg_migrate.py", line 218, in <module>
    main()
  File "aws_sg_migrate.py", line 205, in main
    makesg(profile, sgid, vpcid, source, destination, shell)
  File "aws_sg_migrate.py", line 73, in makesg
    for dest,vpc in destinations.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by Poyeyo** [comment]
Same thing happens to me.

Maybe some change from AWS side?

**Comment by Suncatcher** [comment]
Sorry for delay, guys, I was really busy. Thanks for your feedback, I appreciate it a lot.
Yes, you are absolutely right, it was a change from AWS side that was introduced [in Aug 31 2017](https://aws.amazon.com/blogs/aws/new-descriptions-for-security-group-rules/), just after the moment I wrote the script. Also I actually never tested IP ranges with descriptions.
Just now I released [a new version of script](https://github.com/Suncatcher/aws_sg_migrate/releases/tag/v.0.2) where this was fixed and a bunch of improvements made. Try it, please, and report back.
Though descriptions are still not implemented, I will make it on the next week. Stay in tune.
